# Generated by Django 5.2.5 on 2025-08-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('mood', models.CharField(max_length=20)),
                ('productivity', models.TextField()),
                ('accomplishment', models.TextField()),
                ('stress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('form_submissions', models.ManyToManyField(blank=True, to='form.formsubmission')),
            ],
        ),
    ]
